### ISSUE TITLE
envValue does not accept int

### ISSUE THREAD

**Issue by Nihasa** [common-workflow-language/cwl-v1.2#203]
Trying to inject an integer into the environment from an input value yields the following:

```
'envValue expression must evaluate to a str. Got '6' for expression '$(inputs.threads)'.
```

any minimal .cwl that has includes the following would produce the same error:

```
requirements:
- class: EnvVarRequirement
  envDef: 
    THREADS: $(inputs.threads)

inputs:
  threads:
    doc: |-
      The number of parallel iterations.
    type: string
    default: 4
```

As it is "threads" it should not accept anything other than an integer. I can think of a JS workaround converting it to a string but why exactly can't this be other flat atomic values?
I confirmed that it is indeed only accepting string inputs here:
https://www.commonwl.org/v1.0/CommandLineTool.html#EnvVarRequirement

cwltool version: 3.1.20211107152837
