### ISSUE TITLE
Improve documentation of simplified `[]` and `?` types for advanced use cases

### ISSUE THREAD

**Issue by fmigneault** [common-workflow-language/cwl-v1.2#254]
In https://www.commonwl.org/v1.2/CommandLineTool.html#Document_preprocessing
> 2.4 Document preprocessing
>
> Another transformation defined in Schema salad is simplification of data type definitions. Type <T> ending with ? should be transformed to [<T>, "null"]. Type <T> ending with [] should be transformed to {"type": "array", "items": <T>}

There is no explicit mention of combining the two simplified type definitions.
This leaves room for interpretation.

For example: `string[]?`
Should this be understood as:
1. required array of optional strings, ie:
```yaml
type: array
items: [string, 'null']
```
2. optional array of required strings. ie:
```yaml
type: 
  - type: 'null'
  - type: array
    items: string
```
3. both are optional, ie:
```yaml
type: 
  - type: 'null'
  - type: array
    items: [string, 'null']
```
4. neither (ie: disallowed to combine these shortcuts - I don't think so, because I've used them, but docs should mention it)
5. Can the reverse be applied (ie: `string?[]`) 
    - Does it have the same meaning?
    - Is the order of `?`/`[]` relevant?
