### ISSUE TITLE
document behavior of "in" with/without linkMerge

### ISSUE THREAD

**Issue by tetron** [common-workflow-language/cwl-v1.2#29]
For historical reasons, the de-facto behavior is that these don't do the same thing:

```
in:
  example:
    source: [x]
```

Sets `example` to the value of `x`

```
in:
  example:
    source: [x]
    linkMerge: merge_nested
```

Sets `example` to a single-item array containing the value of `x`.

Ensure this is documented.
