### ISSUE TITLE
Full path in "entryname"

### ISSUE THREAD

**Issue by tetron** [common-workflow-language/cwl-v1.2#37]
I believe it is a de facto behavior of `cwltool` that if `entryname` under InitialWorkDir is a full path and it is running in a Docker container, can mount inputs anywhere on the filesystem that you need to.

I think we discussed this but I can't find any documentation or conformance tests.

This comes up fairly frequently ("how can I control mount points in Docker?") so we should probably formalize it.

**Comment by tetron** [comment]
An example is

```
inputs:
  inputsdir: Directory
requirements:
  DockerRequirement: { dockerPull: image }
  InitialWorkDirRequirement:
    listing:
      - entryname: /inputs
        entry: $(inputs.inputsdir)
```

Will mount `inputsdir` at `/inputs` instead of wherever the runner feels like putting it.
