### ISSUE TITLE
Not logical output from the tool will break the workflow if run as a step

### ISSUE THREAD

**Issue by michael-kotliar** [common-workflow-language/cwl-v1.2#52]
In the following test case from here https://github.com/common-workflow-language/cwl-v1.2/blob/993e40726177b0fe9e0b2484bd3630b3572f6951/conformance_tests.yaml#L6 a tool is expected to return two outputs
```
outputs:
  - id: sam
    type: ["null", File]
    outputBinding: { glob: output.sam }
  - id: args
    type:
      type: array
      items: string
```
where `output.sam` file is a redirected stdout
```
stdout: output.sam
```
That means that `sam` will be always returned even if `output.sam` is empty. However, the python script `args.py` that is run as baseCommand creates `cwl.output.json` file that includes only `args` output. Tool doesn't fail when you run it directly, but will fail if you put it in a workflow and try to return `sam` as a workflow output.
Possible solution, just remove `sam` output from the tool.
